/**
 * Test seed helper (T036b).
 *
 * Writes a minimal but representative dataset to a caller-provided Firestore
 * instance so unit + E2E tests can build on it without re-deriving the schema.
 *
 * Layout seeded (all IDs are Firestore-generated by addDoc):
 *   settings/global
 *     { defaultContributionTarget, openingBalance, currency, moneyOnHand, ... }
 *   households/{hh}
 *     name, createdAt, createdBy
 *   households/{hh}/families/{fid}
 *     name, contributionTarget, active, createdAt, createdBy
 *   households/{hh}/families/{fid}/payments/{pid}
 *     amount, date, month, note, recordedAt, recordedBy
 *   expenses/{eid}
 *     name, amount, date, month, withdrawn, addedAt, addedBy, ...
 *   recurringExpenses/{tid}
 *     name, amount, description, active, createdAt, createdBy
 *
 * Usage:
 *   const db = ...; // emulator-backed Firestore
 *   const seed = await seedTestData(db);
 *   expect(seed.households).toHaveLength(2);
 */
import {
  addDoc,
  collection,
  doc,
  serverTimestamp,
  setDoc,
  type Firestore,
} from "firebase/firestore"
import { toMonthKey } from "@/lib/utils/dates"

const TEST_UID = "seed-tester"

export interface SeedPayment {
  id: string
  householdId: string
  familyId: string
  amount: number
  month: string
}

export interface SeedFamily {
  id: string
  householdId: string
  name: string
  contributionTarget: number
  active: boolean
}

export interface SeedHousehold {
  id: string
  name: string
  families: SeedFamily[]
}

export interface SeedExpense {
  id: string
  name: string
  amount: number
  withdrawn: boolean
  month: string
}

export interface SeedRecurringTemplate {
  id: string
  name: string
  amount: number
  active: boolean
}

export interface SeedSettings {
  openingBalance: number
  defaultContributionTarget: number
  currency: string
  moneyOnHand: number
}

export interface SeedResult {
  settings: SeedSettings
  households: SeedHousehold[]
  payments: SeedPayment[]
  expenses: SeedExpense[]
  recurringTemplates: SeedRecurringTemplate[]
}

export interface SeedOptions {
  asOf?: Date
  defaultContributionTarget?: number
  openingBalance?: number
  currency?: string
  householdDefs?: Array<{ name: string; families: string[] }>
  paymentAmount?: number
  includeExpense?: boolean
  includeRecurring?: boolean
}

const DEFAULT_HOUSEHOLDS: Array<{ name: string; families: string[] }> = [
  { name: "North Ward", families: ["Khan Family", "Patel Family"] },
  { name: "South Ward", families: ["Menon Family", "Rao Family"] },
]

export async function seedTestData(
  db: Firestore,
  options: SeedOptions = {}
): Promise<SeedResult> {
  const asOf = options.asOf ?? new Date()
  const month = toMonthKey(asOf)
  const openingBalance = options.openingBalance ?? 1000
  const defaultContributionTarget = options.defaultContributionTarget ?? 200
  const currency = options.currency ?? "INR"
  const moneyOnHand = openingBalance
  const householdDefs = options.householdDefs ?? DEFAULT_HOUSEHOLDS
  const paymentAmount = options.paymentAmount ?? 100

  // 1. settings/global
  await setDoc(doc(db, "settings", "global"), {
    defaultContributionTarget,
    openingBalance,
    currency,
    moneyOnHand,
    updatedAt: serverTimestamp(),
    updatedBy: TEST_UID,
  })

  // 2. households + families + payments
  const households: SeedHousehold[] = []
  const payments: SeedPayment[] = []

  for (const hhDef of householdDefs) {
    const hhRef = await addDoc(collection(db, "households"), {
      name: hhDef.name,
      createdAt: serverTimestamp(),
      createdBy: TEST_UID,
    })
    const families: SeedFamily[] = []
    for (const familyName of hhDef.families) {
      const famRef = await addDoc(
        collection(db, "households", hhRef.id, "families"),
        {
          name: familyName,
          contributionTarget: defaultContributionTarget,
          active: true,
          createdAt: serverTimestamp(),
          createdBy: TEST_UID,
        }
      )
      families.push({
        id: famRef.id,
        householdId: hhRef.id,
        name: familyName,
        contributionTarget: defaultContributionTarget,
        active: true,
      })
      const payRef = await addDoc(
        collection(
          db,
          "households",
          hhRef.id,
          "families",
          famRef.id,
          "payments"
        ),
        {
          amount: paymentAmount,
          date: asOf,
          month,
          note: null,
          recordedAt: serverTimestamp(),
          recordedBy: TEST_UID,
        }
      )
      payments.push({
        id: payRef.id,
        householdId: hhRef.id,
        familyId: famRef.id,
        amount: paymentAmount,
        month,
      })
    }
    households.push({ id: hhRef.id, name: hhDef.name, families })
  }

  // 3. expenses (optional)
  const expenses: SeedExpense[] = []
  if (options.includeExpense !== false) {
    const expRef = await addDoc(collection(db, "expenses"), {
      name: "Electricity",
      amount: 150,
      date: asOf,
      month,
      note: null,
      isRecurring: false,
      recurringId: null,
      withdrawn: false,
      withdrawnAt: null,
      withdrawnBy: null,
      addedAt: serverTimestamp(),
      addedBy: TEST_UID,
    })
    expenses.push({
      id: expRef.id,
      name: "Electricity",
      amount: 150,
      withdrawn: false,
      month,
    })
  }

  // 4. recurring template (optional)
  const recurringTemplates: SeedRecurringTemplate[] = []
  if (options.includeRecurring !== false) {
    const recRef = await addDoc(collection(db, "recurringExpenses"), {
      name: "Water",
      amount: 50,
      description: "Monthly water bill",
      active: true,
      createdAt: serverTimestamp(),
      createdBy: TEST_UID,
    })
    recurringTemplates.push({
      id: recRef.id,
      name: "Water",
      amount: 50,
      active: true,
    })
  }

  return {
    settings: {
      openingBalance,
      defaultContributionTarget,
      currency,
      moneyOnHand,
    },
    households,
    payments,
    expenses,
    recurringTemplates,
  }
}

/** Wipe everything in the test database. Useful between cases. */
export async function clearTestData(db: Firestore): Promise<void> {
  const { getDocs, deleteDoc, writeBatch } = await import("firebase/firestore")
  const batch = writeBatch(db)
  const collections = [
    "households",
    "expenses",
    "recurringExpenses",
    "settings",
    "admins",
  ]
  for (const col of collections) {
    const snap = await getDocs(collection(db, col))
    for (const d of snap.docs) {
      // For households, also clear subcollections.
      if (col === "households") {
        const famSnap = await getDocs(
          collection(db, col, d.id, "families")
        )
        for (const f of famSnap.docs) {
          const paySnap = await getDocs(
            collection(db, col, d.id, "families", f.id, "payments")
          )
          for (const p of paySnap.docs) batch.delete(p.ref)
          batch.delete(f.ref)
        }
      }
      batch.delete(d.ref)
    }
  }
  await batch.commit()
}
